macro(target_add_sfml TARGET_NAME_ARG)
    find_package(SFML 2.5 COMPONENTS graphics audio window system REQUIRED)
    if(SFML_FOUND)
        target_link_libraries(${TARGET_NAME_ARG} PRIVATE sfml-graphics sfml-audio sfml-window sfml-system)
    else()
        find_package(SFML 2.3 COMPONENTS graphics audio window system)
        if(SFML_FOUND)
            target_include_directories(${TARGET_NAME_ARG} PRIVATE ${SFML_INCLUDE_DIRS})
            target_link_libraries(${TARGET_NAME_ARG} PRIVATE ${SFML_LIBRARIES})
        else()
            message(FATAL_ERROR "SFML could not be found.")
        endif()
    endif()
endmacro(target_add_sfml)
